export const STAGES = [
  "待筛选",
  "待外呼",
  "电销企微培育",
  "销售企微承接",
  "销售跟进",
  "已购会员",
  "VIP维护",
  "续费/复购"
];

export const initialState = {
  selectedCustomerId: "c001",
  agentRuns: [],
  auditLog: [],
  outboundDrafts: [],
  wecomLogs: [],
  personalWechat: {
    enabled: true,
    account: {
      id: "personal_wx_default",
      name: "个人微信托管号",
      displayName: "VIP群AccountAgent",
      defaultCustomerId: "c003",
      autoReply: true,
      requireApprovalForRisk: true,
      minSendIntervalSeconds: 3,
      maxQueueAgeSeconds: 60,
      status: "未连接",
      lastEventAt: "",
      lastError: ""
    },
    groupContexts: [],
    sendJobs: [],
    decisions: [],
    logs: []
  },
  wecomBindings: {
    groups: []
  },
  wecomConfig: {
    enabled: false,
    sendMode: "manualApproval",
    defaultRouteId: "wecom_route_default",
    routes: [
      {
        id: "wecom_route_default",
        name: "企微测试群机器人",
        channel: "VIP群",
        webhookUrl: "",
        msgtype: "markdown",
        enabled: false
      }
    ],
    inbound: {
      enabled: true,
      defaultChannel: "VIP群",
      secret: ""
    },
    aibot: {
      enabled: false,
      botId: "",
      secret: "",
      wsUrl: "",
      defaultCustomerId: "c003",
      defaultChannel: "VIP群",
      autoReply: false,
      welcomeText: "您好，我是客户运营助手，已收到您的消息，会先整理需求并同步给对应同事。",
      heartbeatInterval: 30000,
      maxReconnectAttempts: 10,
      bridgeStatus: "未启动",
      lastConnectedAt: "",
      lastEventAt: "",
      lastError: ""
    }
  },
  modelConfig: {
    global: {
      provider: "DeepSeek兼容网关",
      apiUrl: "https://api.deepseek.com",
      apiKey: "",
      model: "deepseek-v4-flash",
      temperature: 0.2,
      maxTokens: 4096
    },
    voice: {
      asr: {
        provider: "语音识别服务",
        apiUrl: "",
        apiKey: "",
        model: "",
        language: "zh-CN"
      },
      tts: {
        provider: "语音合成服务",
        apiUrl: "",
        apiKey: "",
        model: "",
        voice: "默认",
        speed: 1
      }
    },
    agents: {
      dialer: { provider: "", apiUrl: "", apiKey: "", model: "", temperature: "", maxTokens: "" },
      nurture: { provider: "", apiUrl: "", apiKey: "", model: "", temperature: "", maxTokens: "" },
      sales: { provider: "", apiUrl: "", apiKey: "", model: "", temperature: "", maxTokens: "" },
      vip: { provider: "", apiUrl: "", apiKey: "", model: "", temperature: "", maxTokens: "" },
      quote: { provider: "", apiUrl: "", apiKey: "", model: "", temperature: "", maxTokens: "" },
      orchestrator: { provider: "", apiUrl: "", apiKey: "", model: "", temperature: "", maxTokens: "" }
    }
  },
  salesSamples: [
    {
      id: "ss001",
      scene: "高意向黑金卡成交",
      customerStage: "销售企微承接",
      targetCard: "平台黑金卡",
      objection: "价格敏感",
      outcome: "成交",
      qualityScore: 92,
      tags: ["价格敏感", "高交易额", "稳定货源"],
      phrase: "先不承诺最低价，先帮客户算稳定供货、优先报价和售后协同节省的采购成本，再推进黑金卡权益确认。",
      notes: "适合高交易额、关注稳定货源但压价明显的客户。",
      createdAt: "2026-06-02T09:00:00.000Z"
    },
    {
      id: "ss002",
      scene: "试用卡转正",
      customerStage: "销售跟进",
      targetCard: "平台金卡",
      objection: "权益价值待确认",
      outcome: "成交",
      qualityScore: 86,
      tags: ["试用转正", "iPhone 13", "复购"],
      phrase: "先复盘试用期内报价响应、货源稳定和售后处理，再给出转正式会员后的周度报价和专属群服务承诺。",
      notes: "适合试用卡客户推动转正式会员。",
      createdAt: "2026-06-02T09:10:00.000Z"
    },
    {
      id: "ss003",
      scene: "售后担忧下的会员续费",
      customerStage: "VIP维护",
      targetCard: "续费/增购",
      objection: "售后响应担忧",
      outcome: "继续培育",
      qualityScore: 78,
      tags: ["VIP", "售后频繁", "续费"],
      phrase: "先由售后给出当前问题处理进度，再由私域顾问同步后续响应机制，销售只在问题稳定后推进续费权益。",
      notes: "适合已有会员但近期售后问题较多的客户。",
      createdAt: "2026-06-02T09:20:00.000Z"
    }
  ],
  customers: [
    {
      id: "c001",
      name: "深圳明远数码",
      contact: "陈总",
      phone: "138****5612",
      stage: "电销企微培育",
      owner: "电销一组",
      tradeVolume: 820000,
      purchaseFrequency: 18,
      lastTradeDays: 12,
      memberStatus: "未购卡",
      targetCard: "平台金卡",
      tags: ["iPhone 13", "iPhone 14 Pro", "高频采购", "潜在意向"],
      watchedModels: ["iPhone 13", "iPhone 14 Pro"],
      intentScore: 66,
      risk: "低",
      notes: "长期采购苹果机型，最近询价频率上升，适合从电销培育升级销售承接。"
    },
    {
      id: "c002",
      name: "杭州锐采科技",
      contact: "李经理",
      phone: "136****9021",
      stage: "销售企微承接",
      owner: "销售二组",
      tradeVolume: 1260000,
      purchaseFrequency: 24,
      lastTradeDays: 5,
      memberStatus: "未购卡",
      targetCard: "平台黑金卡",
      tags: ["Mate60", "高交易额", "明确意向", "价格敏感"],
      watchedModels: ["Mate60", "Mate60 Pro"],
      intentScore: 84,
      risk: "低",
      notes: "关注华为高端机型，表达过希望获得稳定报价和优先货源。"
    },
    {
      id: "c003",
      name: "成都华联通讯",
      contact: "周总",
      phone: "139****7781",
      stage: "VIP维护",
      owner: "私域顾问A",
      tradeVolume: 2400000,
      purchaseFrequency: 36,
      lastTradeDays: 2,
      memberStatus: "黑金卡",
      targetCard: "续费/增购",
      tags: ["VIP", "多品牌采购", "售后频繁", "报价订阅"],
      watchedModels: ["iPhone 15", "Mate60", "小米14"],
      intentScore: 78,
      risk: "中",
      notes: "已有会员小群，常在群内直接@销售询问售后和报价问题。"
    },
    {
      id: "c004",
      name: "广州星河商贸",
      contact: "王经理",
      phone: "137****6208",
      stage: "待外呼",
      owner: "待分配",
      tradeVolume: 480000,
      purchaseFrequency: 9,
      lastTradeDays: 38,
      memberStatus: "未购卡",
      targetCard: "平台银卡",
      tags: ["小米14", "低频大额", "待筛选"],
      watchedModels: ["小米14", "Redmi K70"],
      intentScore: 42,
      risk: "低",
      notes: "近期交易放缓，需要外呼确认是否仍有采购计划。"
    },
    {
      id: "c005",
      name: "南京启联供应链",
      contact: "赵总",
      phone: "135****1135",
      stage: "销售跟进",
      owner: "销售一组",
      tradeVolume: 960000,
      purchaseFrequency: 21,
      lastTradeDays: 8,
      memberStatus: "试用卡",
      targetCard: "平台金卡",
      tags: ["配件", "iPhone 13", "试用转正", "明确意向"],
      watchedModels: ["iPhone 13", "AirPods Pro"],
      intentScore: 81,
      risk: "低",
      notes: "正在试用会员权益，需要销售推动转正。"
    },
    {
      id: "c006",
      name: "武汉万桥通讯",
      contact: "刘经理",
      phone: "188****2044",
      stage: "已购会员",
      owner: "私域顾问B",
      tradeVolume: 680000,
      purchaseFrequency: 15,
      lastTradeDays: 19,
      memberStatus: "金卡",
      targetCard: "续费",
      tags: ["金卡", "华为", "报价关注", "需维护"],
      watchedModels: ["Pura 70", "Mate60"],
      intentScore: 58,
      risk: "低",
      notes: "已购金卡，适合进入VIP维护并开启报价订阅。"
    },
    {
      id: "c007",
      name: "苏州云启通讯",
      contact: "张总",
      phone: "133****7810",
      stage: "待筛选",
      owner: "待分配",
      tradeVolume: 350000,
      purchaseFrequency: 7,
      lastTradeDays: 61,
      memberStatus: "未购卡",
      targetCard: "平台银卡",
      tags: ["OPPO", "Redmi", "低频采购", "待筛选"],
      watchedModels: ["OPPO Find X7", "Redmi K70"],
      intentScore: 35,
      risk: "低",
      notes: "历史交易稳定但近期沉默，适合先做低成本筛选。"
    },
    {
      id: "c008",
      name: "天津博瑞数码",
      contact: "马经理",
      phone: "186****3391",
      stage: "待外呼",
      owner: "电销二组",
      tradeVolume: 720000,
      purchaseFrequency: 14,
      lastTradeDays: 22,
      memberStatus: "未购卡",
      targetCard: "平台金卡",
      tags: ["vivo", "小米14", "可培育", "价格关注"],
      watchedModels: ["vivo X100", "小米14"],
      intentScore: 53,
      risk: "低",
      notes: "多次询价但未表达会员需求，需要外呼判断真实采购节奏。"
    },
    {
      id: "c009",
      name: "厦门海盛电子",
      contact: "林总",
      phone: "189****6402",
      stage: "电销企微培育",
      owner: "电销二组",
      tradeVolume: 1080000,
      purchaseFrequency: 19,
      lastTradeDays: 9,
      memberStatus: "未购卡",
      targetCard: "平台金卡",
      tags: ["iPhone 15", "高频采购", "报价敏感", "潜在意向"],
      watchedModels: ["iPhone 15", "iPhone 15 Pro"],
      intentScore: 70,
      risk: "低",
      notes: "近期频繁关注苹果报价，适合用报价订阅推动加深沟通。"
    },
    {
      id: "c010",
      name: "青岛远帆贸易",
      contact: "宋经理",
      phone: "151****2286",
      stage: "销售企微承接",
      owner: "销售一组",
      tradeVolume: 1800000,
      purchaseFrequency: 28,
      lastTradeDays: 4,
      memberStatus: "未购卡",
      targetCard: "平台黑金卡",
      tags: ["高交易额", "Apple", "华为", "明确意向"],
      watchedModels: ["iPhone 15 Pro", "Mate60 Pro"],
      intentScore: 88,
      risk: "中",
      notes: "交易体量高，要求稳定货源和售后响应，需要销售快速承接。"
    },
    {
      id: "c011",
      name: "郑州星联数码",
      contact: "郭总",
      phone: "152****7609",
      stage: "销售跟进",
      owner: "销售三组",
      tradeVolume: 900000,
      purchaseFrequency: 17,
      lastTradeDays: 13,
      memberStatus: "试用卡",
      targetCard: "平台金卡",
      tags: ["Pura 70", "试用转正", "售后关注"],
      watchedModels: ["Pura 70", "Mate60"],
      intentScore: 76,
      risk: "低",
      notes: "试用期内询价活跃，主要担心售后响应，适合销售配合私域推进转正。"
    },
    {
      id: "c012",
      name: "西安鼎新通讯",
      contact: "何经理",
      phone: "177****4280",
      stage: "已购会员",
      owner: "私域顾问C",
      tradeVolume: 1400000,
      purchaseFrequency: 25,
      lastTradeDays: 6,
      memberStatus: "金卡",
      targetCard: "续费",
      tags: ["金卡", "小米14", "华为", "需维护"],
      watchedModels: ["小米14", "Pura 70"],
      intentScore: 62,
      risk: "低",
      notes: "已购金卡但群内互动少，需要私域定期推送关注型号报价。"
    },
    {
      id: "c013",
      name: "北京华北渠道",
      contact: "许总",
      phone: "139****0701",
      stage: "VIP维护",
      owner: "私域顾问D",
      tradeVolume: 3200000,
      purchaseFrequency: 42,
      lastTradeDays: 1,
      memberStatus: "黑金卡",
      targetCard: "续费/增购",
      tags: ["黑金卡", "大客户", "多品牌采购", "售后敏感"],
      watchedModels: ["iPhone 16", "Mate70", "小米14 Ultra"],
      intentScore: 83,
      risk: "中",
      notes: "高价值VIP客户，售后和报价问题都要求高响应，需要群内分流和报价订阅。"
    },
    {
      id: "c014",
      name: "上海睿采供应链",
      contact: "沈总",
      phone: "138****9018",
      stage: "续费/复购",
      owner: "销售二组",
      tradeVolume: 2700000,
      purchaseFrequency: 33,
      lastTradeDays: 3,
      memberStatus: "黑金卡",
      targetCard: "续费/增购",
      tags: ["续费", "高交易额", "Apple", "报价关注"],
      watchedModels: ["iPhone 15", "iPhone 16"],
      intentScore: 89,
      risk: "低",
      notes: "会员即将到期，近期仍有高频采购，适合销售准备续费方案。"
    },
    {
      id: "c015",
      name: "合肥联创通信",
      contact: "曹经理",
      phone: "180****4566",
      stage: "待筛选",
      owner: "待分配",
      tradeVolume: 260000,
      purchaseFrequency: 5,
      lastTradeDays: 75,
      memberStatus: "未购卡",
      targetCard: "平台银卡",
      tags: ["realme", "低交易额", "待筛选"],
      watchedModels: ["realme GT", "Redmi K70"],
      intentScore: 28,
      risk: "低",
      notes: "采购频次偏低，先确认是否还有平台采购需求。"
    },
    {
      id: "c016",
      name: "佛山南粤数码",
      contact: "梁总",
      phone: "137****8783",
      stage: "待外呼",
      owner: "电销一组",
      tradeVolume: 610000,
      purchaseFrequency: 12,
      lastTradeDays: 30,
      memberStatus: "未购卡",
      targetCard: "平台银卡",
      tags: ["荣耀", "小米", "待外呼", "价格关注"],
      watchedModels: ["荣耀Magic6", "小米14"],
      intentScore: 47,
      risk: "中",
      notes: "询价后未继续沟通，需要外呼确认价格敏感原因。"
    },
    {
      id: "c017",
      name: "长沙易采科技",
      contact: "邓经理",
      phone: "181****5690",
      stage: "电销企微培育",
      owner: "电销三组",
      tradeVolume: 1120000,
      purchaseFrequency: 20,
      lastTradeDays: 10,
      memberStatus: "未购卡",
      targetCard: "平台金卡",
      tags: ["Mate60", "Pura 70", "潜在意向", "高频采购"],
      watchedModels: ["Mate60", "Pura 70"],
      intentScore: 72,
      risk: "低",
      notes: "对华为报价响应快，适合继续推送型号报价并观察是否升级销售。"
    },
    {
      id: "c018",
      name: "重庆九舟通讯",
      contact: "唐总",
      phone: "185****6933",
      stage: "销售企微承接",
      owner: "销售三组",
      tradeVolume: 1560000,
      purchaseFrequency: 26,
      lastTradeDays: 7,
      memberStatus: "未购卡",
      targetCard: "平台黑金卡",
      tags: ["iPhone 15", "iPhone 14 Pro", "明确意向", "稳定货源"],
      watchedModels: ["iPhone 15", "iPhone 14 Pro"],
      intentScore: 86,
      risk: "低",
      notes: "明确提到希望锁定稳定货源，但需要解释黑金卡权益边界。"
    }
  ],
  events: [
    {
      id: "e001",
      customerId: "c001",
      channel: "模拟企微私聊",
      type: "客户回复",
      text: "最近 iPhone 13 还有稳定报价吗？会员卡能不能便宜点？",
      time: "09:18"
    },
    {
      id: "e002",
      customerId: "c003",
      channel: "VIP模拟群",
      type: "群内提问",
      text: "@销售 上周那批 Mate60 有两台售后怎么处理？顺便今天报价发一下。",
      time: "09:42"
    },
    {
      id: "e003",
      customerId: "c002",
      channel: "销售模拟私聊",
      type: "客户回复",
      text: "如果黑金卡能保证优先报价和稳定货源，我这周可以定。",
      time: "10:06"
    }
  ],
  conversations: [
    {
      id: "conv_c003_vip",
      customerId: "c003",
      channel: "VIP模拟群",
      title: "成都华联通讯会员小群",
      members: [
        { name: "周总", role: "客户" },
        { name: "私域顾问A", role: "私域" },
        { name: "销售二组", role: "销售" },
        { name: "客服值班", role: "客服" },
        { name: "售后值班", role: "售后" }
      ],
      messages: [
        {
          id: "m001",
          sender: "周总",
          senderRole: "客户",
          text: "@销售 上周那批 Mate60 有两台售后怎么处理？顺便今天报价发一下。",
          mentions: ["销售"],
          time: "09:42",
          createdAt: "2026-06-02T09:42:00.000Z"
        },
        {
          id: "m002",
          sender: "私域顾问A",
          senderRole: "私域",
          text: "我先同步售后值班看维修进度，报价部分稍后给您更新。",
          mentions: ["售后"],
          time: "09:45",
          createdAt: "2026-06-02T09:45:00.000Z"
        }
      ]
    }
  ],
  tasks: [
    {
      id: "t001",
      customerId: "c002",
      title: "黑金卡高意向承接",
      ownerRole: "销售",
      owner: "销售二组",
      priority: "高",
      status: "跟进中",
      sla: "2小时",
      reason: "客户明确表达本周可定，关注稳定货源。"
    },
    {
      id: "t002",
      customerId: "c003",
      title: "VIP群售后问题分流",
      ownerRole: "售后",
      owner: "售后值班",
      priority: "高",
      status: "待处理",
      sla: "30分钟",
      reason: "客户错@销售，但问题核心是售后处理。"
    }
  ],
  templates: [
    {
      id: "tpl_welcome",
      scene: "企微添加引导",
      name: "企微欢迎语",
      allowed: true,
      risk: "低",
      content: "您好，{客户称呼}，我是{团队}的智能助手，后续会同步您关注的{关注型号}和会员权益信息。"
    },
    {
      id: "tpl_nurture_model",
      scene: "电销企微培育",
      name: "型号报价提醒",
      allowed: true,
      risk: "低",
      content: "{客户称呼}，您关注的{关注型号}本周有新报价，可先看报价页，也可以回复我让销售跟进。"
    },
    {
      id: "tpl_sales_handoff",
      scene: "销售承接",
      name: "销售接入提醒",
      allowed: true,
      risk: "中",
      content: "我已帮您整理需求，{销售}会继续跟进{会员卡}权益和报价细节。"
    },
    {
      id: "tpl_vip_route",
      scene: "VIP群分流",
      name: "群问题分流",
      allowed: true,
      risk: "低",
      content: "已识别这是{问题类型}，我会同步给{处理角色}处理，并在{SLA}内更新进度。"
    },
    {
      id: "tpl_price_commit",
      scene: "价格承诺",
      name: "价格锁定承诺",
      allowed: false,
      risk: "高",
      content: "该模板禁用：任何锁价、合同、付款、退款承诺必须人工确认。"
    }
  ],
  quotes: [
    { id: "q001", brand: "Apple", model: "iPhone 13", config: "128G", price: 3780, stock: "充足", validUntil: "2026-06-07" },
    { id: "q002", brand: "Apple", model: "iPhone 14 Pro", config: "256G", price: 5960, stock: "少量", validUntil: "2026-06-07" },
    { id: "q003", brand: "Apple", model: "iPhone 15", config: "128G", price: 5140, stock: "稳定", validUntil: "2026-06-07" },
    { id: "q004", brand: "Huawei", model: "Mate60", config: "256G", price: 5480, stock: "稳定", validUntil: "2026-06-06" },
    { id: "q005", brand: "Huawei", model: "Mate60 Pro", config: "512G", price: 6860, stock: "紧张", validUntil: "2026-06-06" },
    { id: "q006", brand: "Xiaomi", model: "小米14", config: "256G", price: 3180, stock: "充足", validUntil: "2026-06-08" },
    { id: "q007", brand: "Huawei", model: "Pura 70", config: "256G", price: 4690, stock: "稳定", validUntil: "2026-06-08" },
    { id: "q008", brand: "Accessories", model: "AirPods Pro", config: "二代", price: 1280, stock: "充足", validUntil: "2026-06-09" }
  ]
};
